// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEAtNHtkfVPAV3kya7ESmH3Kz34gSNoy0',
    appId: '1:772234361336:android:8dc744131393754f753e0d',
    messagingSenderId: '772234361336',
    projectId: 'notify-afb86',
    storageBucket: 'notify-afb86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkfOI-xuwTlMkmH8NSdzKuB1-Y4AHNAfw',
    appId: '1:772234361336:ios:da0d75c4e1e978c6753e0d',
    messagingSenderId: '772234361336',
    projectId: 'notify-afb86',
    storageBucket: 'notify-afb86.appspot.com',
    androidClientId: '772234361336-ilgsg62me9tgsbes1rh7vl44a9l3mps7.apps.googleusercontent.com',
    iosClientId: '772234361336-ae6iefk5e7duur14pj5p115uct6jefln.apps.googleusercontent.com',
    iosBundleId: 'com.example.notify',
  );
}
